name: "Deploy dev&prod"
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"
#      - "dev-*"

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    env:
      NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    steps:
      - uses: "actions/checkout@v5"
      - name: Enable Corepack
        run: corepack enable
      - uses: "actions/setup-node@v5"
        with:
          node-version: 22
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"

      - name: "Install dependencies"
        run: "yarn --immutable"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: "Tests"
        run: "yarn run test"

      - name: "Build application"
        run: "yarn run build"

      - name: "Upload to cdn"
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: aap # Change this to your team name
          source: ./dist/client/_astro
          destination: "aap-min-side-microfrontend"

      - name: "Build and push"
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: aap # Change this to your team name

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  update-manifest-dev:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@main
    needs: build
    with:
      id: "aap-min-side-microfrontend" # Change this to your microfrontend id.
      url: "http://aap-min-side-microfrontend.aap" # Change the url to contain your application name. Example: http://my-app.namespace
      appname: "aap-min-side-microfrontend" # Change this to your application name
      namespace: "aap" # Change this to your namespace
      cluster: dev-gcp
      commitmsg: ${{ github.event.head_commit.message}}
      fallback: "fallback" # Should containt the path to the fallback page after src/pages/[locale]/... Only needs to be changed if you move the fallback in the pages structure
      ssr: true
    secrets: inherit

  # update-manifest-prod:
  #   if: github.ref == 'refs/heads/main'
  #   uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v3.yaml@main
  #   needs: build
  #   with:
  #     id: "tms-microfrontend-template-ssr-id"
  #     url: "http://tms-microfrontend-template-ssr.min-side"
  #     appname: "tms-microfrontend-template-ssr"
  #     namespace: "team-namespace"
  #     cluster: prod-gcp
  #     commitmsg: ${{ github.event.head_commit.message}}
  #     fallback: "fallback" # Should containt the path to the fallback page after src/pages/[locale]/...
  #     ssr: true
  #   secrets: inherit

  deploy-dev:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    needs: [build, update-manifest-dev]
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to dev"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp/nais.yaml
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}

  # deploy-prod:
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: "ubuntu-latest"
  #   permissions:
  #     contents: "read"
  #     id-token: "write"
  #   needs: [build, update-manifest-prod]

  #   steps:
  #     - uses: "actions/checkout@v4"
  #     - name: "Deploy to prod"
  #       uses: "nais/deploy/actions/deploy@v2"
  #       env:
  #         CLUSTER: prod-gcp
  #         RESOURCE: nais/prod-gcp/nais.yaml
  #         VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
